### PR TITLE
client orders/thank you page with features 👍🏼 

### PR DESCRIPTION
**Pull request by TWcamel**
https://camel.memery.app/
https://camel.memery.app/attraction/3
https://camel.memery.app/booking

👉🏼 feature1: Shopping cart for client orders
👉🏼 feature2: TapPay with direct pay API but not field API for better looking
👉🏼 feature3: Not allow client to pay an order if contact or TapPay not valid
👉🏼 feature4: Backend multi-thread for api calls

☑️ TODOs: check [here](https://github.com/TWcamel/taipei-day-trip-website/blob/develop/README.md)

### CODE REVIEW

**Comment by cwpeng** [comment]
We should show message for user when there is no booking data.

未命名-2

**Comment by TWcamel** [comment]
Sorry, It's just a CSS issue. The display has been fixed, please check it again. Thanks for your help.

Screen Shot 2022-04-12 at 3 26 17 AM

May good health takes care of you :),

BRs.

**Comment by cwpeng** [comment]
OK. GOOD. :)

**Comment by TWcamel** [comment]
Hi Peng, since you didn't approve the required review, so I can't merge to master 😅

**Review by cwpeng — APPROVED** [review]
Sorry for that. It's approved.

**Pull request merged**
