### PR TITLE
attraction page is finished, please check it 👍🏼 

### PR DESCRIPTION
**Pull request by TWcamel**
http://44.199.53.184:3000
http://44.199.53.184:3000/attraction/1
DC:TWcamel/黃上科

### CODE REVIEW

**Comment by cwpeng** [comment]
Try to align with design more carefully.

1. Font size and padding of 開始預定行程 button.
2. Radio button fill color of 選擇時間.
3. Left arrow and right arrow of image slide should be wrapped in a circle (will be more visible in any background)

**Comment by TWcamel** [comment]
Sorry for the wrongly design 
I've already fix the above CSS. Please check it again. Thanks :)

**Comment by cwpeng** [comment]
I see no significant improvements. Check screenshot below.

未命名-2

**Comment by TWcamel** [comment]
image

http://44.199.53.184:3000/
http://44.199.53.184:3000/attraction/1

Sorry, I just forgot to upload files.... (want to kill myself QQ)

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
